### ISSUE TITLE
input_format txt breaks with urls with commas

### ISSUE THREAD

**Issue by nbardy** [rom1504/img2dataset#208] opened 2022-09-24 05:10 UTC
This url with a comma is breaking the csv reader for txt files.

Might be better to just load the data and split lines instead of using a csv loader

https://github.com/rom1504/img2dataset/blob/c0f14c9020003483f9b30b960317187f9a6c6b97/img2dataset/reader.py#L72

https://static.wixstatic.com/media/c812a4_94ab051187d34f21909ec71b02b3126b~mv2.jpg/v1/fill/w_303,h_170,al_c,q_90,blur_2/Nazar%C3%A9_big_wave.jpg

**Comment by rom1504** [comment] 2022-09-24 07:57
What dataset are you using?

I highly advise to use parquet if you have a choice
Csv is a bad format

**Comment by rom1504** [comment] 2022-09-24 07:57
Duplicate of https://github.com/rom1504/img2dataset/issues/196

**Closed by rom1504** 2022-09-24 07:57 UTC
